### ISSUE TITLE
Error importing SECEdgar libraries, maybe wrong html5lib version?

### ISSUE THREAD

**Issue by hunsbea** [coyo8/sec-edgar#71]
**Describe the bug**
Getting an error when trying to import the library, as per the documentation. Looks like something may have changed inside html5lib? May need to specify which version you're using in the requirements.txt.
Edit: I'm using html5lib==1.0.1

**To Reproduce**
```
$ pip3 install SECEdgar
Requirement already satisfied: SECEdgar in /usr/local/lib/python3.6/site-packages/SECEdgar-0.1.4-py3.6.egg (0.1.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.6/site-packages (from SECEdgar) (4.4.0)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from SECEdgar) (2.22.0)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->SECEdgar) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->SECEdgar) (2017.11.5)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->SECEdgar) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->SECEdgar) (3.0.4)
$ python3
Python 3.6.5 (default, Jun 17 2018, 12:26:58) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from SECEdgar.filings import Filing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SECEdgar-0.1.4-py3.6.egg/SECEdgar/filings/__init__.py", line 1, in <module>
    from SECEdgar.base import _EDGARBase  # noqa:F401
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/SECEdgar-0.1.4-py3.6.egg/SECEdgar/base.py", line 1, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
>>>
```
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
If specific to your OS, please specify which OS you are using [e.g. Windows, macOS, Ubuntu Linux, etc.]

**Additional context**

**Comment by jackmoody11** [comment]
Have you tried updating the beautiful soup and html5lib packages? Take a look at [this SO post](https://stackoverflow.com/questions/38447738/beautifulsoup-html5lib-module-object-has-no-attribute-base) and let me know if that resolves the issue.

```
pip3 install --upgrade beautifulsoup4
pip3 install --upgrade html5lib
```

**Comment by jackmoody11** [comment]
Travis is using setup.py for testing and this doesn't seem to be a problem, so I am going to close this. If this problem persists, feel free to open another issue referencing this thread.
